{{- if .Values.monitoring.enabled }}
{{- $prometheusName := include "mind-journal.prometheus.fullname" . -}}
{{- $frontendName := include "mind-journal.frontend.fullname" . -}}
{{- $gatewayName := include "mind-journal.gateway.fullname" . -}}
{{- $authName := include "mind-journal.auth.fullname" . -}}
{{- $wellnessName := include "mind-journal.wellness.fullname" . -}}
{{- $wellnessWorkerName := include "mind-journal.wellness-worker.fullname" . -}}
{{- $mailName := include "mind-journal.mail.fullname" . -}}
{{- $lokiName := include "mind-journal.loki.fullname" . -}}
{{- $promtailName := include "mind-journal.promtail.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $prometheusName }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    {{- include "mind-journal.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
    scrape_configs:
      - job_name: frontend
        metrics_path: /api/metrics
        static_configs:
          - targets: ["{{ $frontendName }}:{{ .Values.frontend.service.httpPort }}"]
      - job_name: gateway
        metrics_path: /api/metrics
        static_configs:
          - targets: ["{{ $gatewayName }}:{{ .Values.gateway.service.httpPort }}"]
      - job_name: auth
        metrics_path: /metrics
        static_configs:
          - targets: ["{{ $authName }}:{{ .Values.auth.service.httpPort }}"]
      - job_name: wellness
        metrics_path: /metrics
        static_configs:
          - targets: ["{{ $wellnessName }}:{{ .Values.wellness.service.httpPort }}"]
      - job_name: wellness-worker
        metrics_path: /metrics
        static_configs:
          - targets: ["{{ $wellnessWorkerName }}:{{ (index .Values "wellness-worker").service.httpPort }}"]
      - job_name: mail
        metrics_path: /metrics
        static_configs:
          - targets: ["{{ $mailName }}:{{ .Values.mail.service.httpPort }}"]
      - job_name: loki
        metrics_path: /metrics
        static_configs:
          - targets: ["{{ $lokiName }}:3100"]
      - job_name: promtail
        metrics_path: /metrics
        static_configs:
          - targets: ["{{ $promtailName }}:9080"]
{{- end }}
