from typing import Protocol

from dto import request as request_dto
from dto import response as response_dto


class AuthRepositoryProtocol(Protocol):
    async def register(self, data: request_dto.RegisterRequestDTO) -> str: ...

    async def confirm_email(self, user_id: str) -> None: ...

    async def reset_password(
        self, data: request_dto.ResetPasswordRequestDTO
    ) -> list[str]: ...

    async def log_in(self, data: request_dto.LogInDataRequestDTO) -> None: ...

    async def log_out(self, access_token: str) -> None: ...

    async def refresh(self, data: request_dto.RefreshDataRequestDTO) -> str: ...

    async def session_list(
        self, user_id: str
    ) -> list[response_dto.SessionInfoResponseDTO]: ...

    async def revoke_session(self, session_id: str) -> str: ...

    async def validate_access_token(self, access_token: str) -> None: ...

    async def profile_by_user_id(
        self, user_id: str
    ) -> response_dto.ProfileResponseDTO: ...

    async def profile_by_username(
        self, username: str
    ) -> response_dto.ProfileResponseDTO: ...

    async def profile_by_email(self, email: str) -> response_dto.ProfileResponseDTO: ...

    async def update_email(
        self, data: request_dto.UpdateEmailDataRequestDTO
    ) -> str: ...

    async def update_password(
        self, data: request_dto.UpdatePasswordDataRequestDTO
    ) -> list[str]: ...

    async def delete_profile(self, user_id: str) -> list[str]: ...
