from enum import Enum


class Metric(Enum):
    MOOD = 0
    SLEEP_HOURS = 1
    ACTIVITY = 2
    STRESS = 3
    ENERGY = 4
    FOCUS = 5


class Period(Enum):
    WEEK = 0
    MONTH = 1
    QUARTER = 2
    HALF_YEAR = 3
    YEAR = 4


class Priority(Enum):
    HIGH = 0
    MEDIUM = 1
    LOW = 2


class AnalyticsLevel(Enum):
    BASIC = 0
    INTERMEDIATE = 1
    ADVANCED = 2


class Insight(Enum):
    # MOOD
    LOW_MOOD = 0
    HIGH_MOOD = 1
    MOOD_TREND_UP = 2
    MOOD_TREND_DOWN = 3
    MOOD_STABLE = 4
    MOOD_ABOVE_AVG = 5
    MOOD_BELOW_AVG = 6
    UNUSUAL_HIGH_MOOD = 7
    UNUSUAL_LOW_MOOD = 8
    MOOD_EXPECTED_UP = 9
    MOOD_EXPECTED_DOWN = 10
    MOOD_EXPECTED_STABLE = 11

    # SLEEP
    LOW_SLEEP = 12
    HIGH_SLEEP = 13
    IRREGULAR_SLEEP = 14
    SLEEP_TREND_UP = 15
    SLEEP_TREND_DOWN = 16
    SLEEP_STABLE = 17
    SLEEP_ABOVE_AVG = 18
    SLEEP_BELOW_AVG = 19
    UNUSUAL_HIGH_SLEEP = 20
    UNUSUAL_LOW_SLEEP = 21

    # ACTIVITY
    LOW_ACTIVITY = 22
    HIGH_ACTIVITY = 23
    ACTIVITY_TREND_UP = 24
    ACTIVITY_TREND_DOWN = 25
    ACTIVITY_STABLE = 26
    ACTIVITY_ABOVE_AVG = 27
    ACTIVITY_BELOW_AVG = 28
    UNUSUAL_HIGH_ACTIVITY = 29
    UNUSUAL_LOW_ACTIVITY = 30

    # STRESS
    HIGH_STRESS = 31
    LOW_STRESS = 32
    STRESS_TREND_UP = 33
    STRESS_TREND_DOWN = 34
    STRESS_STABLE = 35
    STRESS_ABOVE_AVG = 36
    STRESS_BELOW_AVG = 37
    UNUSUAL_HIGH_STRESS = 38
    UNUSUAL_LOW_STRESS = 39
    STRESS_EXPECTED_UP = 40
    STRESS_EXPECTED_DOWN = 41

    # ENERGY
    LOW_ENERGY = 42
    HIGH_ENERGY = 43
    ENERGY_TREND_UP = 44
    ENERGY_TREND_DOWN = 45
    ENERGY_STABLE = 46
    ENERGY_ABOVE_AVG = 47
    ENERGY_BELOW_AVG = 48
    UNUSUAL_HIGH_ENERGY = 49
    UNUSUAL_LOW_ENERGY = 50
    ENERGY_EXPECTED_UP = 51
    ENERGY_EXPECTED_DOWN = 52

    # FOCUS
    LOW_FOCUS = 53
    HIGH_FOCUS = 54
    FOCUS_TREND_UP = 55
    FOCUS_TREND_DOWN = 56
    FOCUS_STABLE = 57
    FOCUS_ABOVE_AVG = 58
    FOCUS_BELOW_AVG = 59
    UNUSUAL_HIGH_FOCUS = 60
    UNUSUAL_LOW_FOCUS = 61


class Recommendation(Enum):
    # MOOD
    DO_SOMETHING_FUN = 0
    SOCIAL_CONNECTION = 1
    GRATITUDE_PRACTICE = 2

    # SLEEP
    IMPROVE_SLEEP_HYGIENE = 3
    FIXED_BEDTIME = 4
    AVOID_SCREENS_BEFORE_BED = 5

    # ACTIVITY
    TAKE_WALK = 6
    LIGHT_EXERCISE = 7
    STRETCHING = 8

    # STRESS
    BREATHING_EXERCISE = 9
    MEDITATION = 10
    MINDFULNESS = 11

    # ENERGY
    BOOST_ENERGY = 12
    HYDRATION = 13
    POWER_NAP = 14

    # FOCUS
    POMODORO_TECHNIQUE = 15
    TAKE_BREAKS = 16
    MINIMIZE_DISTRACTIONS = 17

    # GENERAL
    MAINTAIN_GOOD_HABITS = 18
    CONTINUE_POSITIVE_TREND = 19

    # FEATURE IMPORTANCE
    FOCUS_ON_SLEEP = 20
    FOCUS_ON_ACTIVITY = 21
    FOCUS_ON_STRESS = 22
    FOCUS_ON_ENERGY = 23
    FOCUS_ON_FOCUS = 24

    # PREVENTIVE
    PREVENT_BURNOUT = 25
    MORNING_SUNLIGHT = 26
    EVENING_WIND_DOWN = 27
