services:
  frontend:
    image: frontend:test
    env_file:
      - ./test/.env.frontend
    environment:
      - API_URL=http://gateway:8000/api
    command: npm test
    container_name: frontend_test

  gateway:
    image: gateway:test
    env_file:
      - ./test/.env
    command: sh -c "uv run --group test pytest ./tests --cov=. --cov-config=./tests/.coveragerc --cov-report=xml --cov-fail-under=100"
    container_name: gateway_test

  auth:
    image: auth:test
    env_file:
      - ./test/.env
    command: sh -c "uv run --group test pytest ./tests --cov=. --cov-config=./tests/.coveragerc --cov-report=xml --cov-fail-under=100"
    container_name: auth_test

  wellness:
    image: wellness:test
    env_file:
      - ./test/.env
    command: sh -c "uv run --group test pytest ./tests --cov=. --cov-config=./tests/.coveragerc --cov-report=xml --cov-fail-under=75"
    container_name: wellness_test

  mail:
    image: mail:test
    env_file:
      - ./test/.env
    command: sh -c "uv run --group test pytest ./tests --cov=. --cov-config=./tests/.coveragerc --cov-report=xml --cov-fail-under=100"
    container_name: mail_test
