{{- if .Values.secrets.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mind-journal.auth.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: auth
    {{- include "mind-journal.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.auth }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
