apiVersion: v1
kind: Service
metadata:
  name: {{ include "mind-journal.auth.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: auth
    {{- include "mind-journal.labels" . | nindent 4 }}
spec:
  selector:
    app: auth
  ports:
  - name: grpc
    port: {{ .Values.auth.service.grpcPort }}
    targetPort: grpc
  - name: http
    port: {{ .Values.auth.service.httpPort }}
    targetPort: http
  type: ClusterIP
