apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mind-journal.mail.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: mail
    {{- include "mind-journal.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.mail.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  KAFKA_SERVICE: {{ include "mind-journal.kafka.fullname" . }}:9092
