apiVersion: v1
kind: Service
metadata:
  name: {{ include "mind-journal.mail.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mail
    {{- include "mind-journal.labels" . | nindent 4 }}
spec:
  selector:
    app: mail
  ports:
  - name: http
    port: {{ .Values.mail.service.httpPort }}
    targetPort: http
  type: ClusterIP
