environment: prod

monitoring:
  enabled: true

ingress:
  tls:
    enabled: true
    secretName: mind-journal-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

frontend:
  replicaCount: 2
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: "1"

gateway:
  replicaCount: 2
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: "1"
  env:
    APP_NAME: MindJournal
    VERSION: "1.0.0"
    DEBUG: "0"

auth:
  replicaCount: 2
  image:
    tag: auth-latest
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: "1"
  env:
    APP_NAME: MindJournal
    DEBUG: "0"
    POSTGRES_DB: mind_journal
    REDIS_DB: "0"
    REDIS_USER: default

auth-postgres:
  userDatabase:
    name:
      value: mind_journal
  persistence:
    size: 10Gi
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: "1"

auth-redis:
  persistence:
    size: 5Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

wellness:
  replicaCount: 2
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: "1"
  env:
    WORKER_DEBUG: "0"
    POSTGRES_DB: mind_journal
    REDIS_DB: "0"
    REDIS_USER: default

wellness-worker:
  replicaCount: 2
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: "1"
  env:
    WORKER_DEBUG: "0"
    POSTGRES_DB: mind_journal
    REDIS_DB: "0"
    REDIS_USER: default

wellness-postgres:
  userDatabase:
    name:
      value: mind_journal
  persistence:
    size: 20Gi
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: "1"

wellness-redis:
  persistence:
    size: 5Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

mail:
  replicaCount: 2
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: "1"
  env:
    APP_NAME: MindJournal

kafka:
  controller:
    persistence:
      size: 10Gi

prometheus:
  storage: 5Gi

loki:
  storage: 25Gi

grafana:
  storage: 5Gi
