apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mind-journal.frontend.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
    {{- include "mind-journal.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.frontend.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  API_URL: http://{{ include "mind-journal.gateway.fullname" . }}:{{ .Values.gateway.service.httpPort }}/api
