{{- if (index .Values "auth-postgres").userDatabase.password.value }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: auth-postgres
    {{- include "mind-journal.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ (index .Values "auth-postgres").userDatabase.password.value | b64enc | quote }}
{{- end }}

---

{{- if (index .Values "auth-redis").redisConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: auth-redis
    {{- include "mind-journal.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ (index .Values "auth-redis").auth.password | b64enc | quote }}
{{- end }}

---

{{- if (index .Values "wellness-postgres").userDatabase.password.value }}
apiVersion: v1
kind: Secret
metadata:
  name: wellness-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: wellness-postgres
    {{- include "mind-journal.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ (index .Values "wellness-postgres").userDatabase.password.value | b64enc | quote }}
{{- end }}

---

{{- if (index .Values "wellness-redis").redisConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: wellness-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: wellness-redis
    {{- include "mind-journal.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ (index .Values "wellness-redis").auth.password | b64enc | quote }}
{{- end }}
