# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from . import wellness_pb2 as wellness__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in wellness_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class WellnessStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpsertRecord = channel.unary_unary(
            "/wellness.Wellness/UpsertRecord",
            request_serializer=wellness__pb2.UpsertRecordRequest.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.RecordList = channel.unary_unary(
            "/wellness.Wellness/RecordList",
            request_serializer=wellness__pb2.Month.SerializeToString,
            response_deserializer=wellness__pb2.RecordListResponse.FromString,
            _registered_method=True,
        )
        self.DeleteAll = channel.unary_unary(
            "/wellness.Wellness/DeleteAll",
            request_serializer=wellness__pb2.UserId.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.Dashboard = channel.unary_unary(
            "/wellness.Wellness/Dashboard",
            request_serializer=wellness__pb2.DashboardRequest.SerializeToString,
            response_deserializer=wellness__pb2.DashboardResponse.FromString,
            _registered_method=True,
        )
        self.Analytics = channel.unary_unary(
            "/wellness.Wellness/Analytics",
            request_serializer=wellness__pb2.UserId.SerializeToString,
            response_deserializer=wellness__pb2.AnalyticsResponse.FromString,
            _registered_method=True,
        )
        self.Recommendations = channel.unary_unary(
            "/wellness.Wellness/Recommendations",
            request_serializer=wellness__pb2.UserId.SerializeToString,
            response_deserializer=wellness__pb2.RecommendationsResponse.FromString,
            _registered_method=True,
        )


class WellnessServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpsertRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RecordList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Dashboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Analytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Recommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WellnessServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "UpsertRecord": grpc.unary_unary_rpc_method_handler(
            servicer.UpsertRecord,
            request_deserializer=wellness__pb2.UpsertRecordRequest.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "RecordList": grpc.unary_unary_rpc_method_handler(
            servicer.RecordList,
            request_deserializer=wellness__pb2.Month.FromString,
            response_serializer=wellness__pb2.RecordListResponse.SerializeToString,
        ),
        "DeleteAll": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteAll,
            request_deserializer=wellness__pb2.UserId.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "Dashboard": grpc.unary_unary_rpc_method_handler(
            servicer.Dashboard,
            request_deserializer=wellness__pb2.DashboardRequest.FromString,
            response_serializer=wellness__pb2.DashboardResponse.SerializeToString,
        ),
        "Analytics": grpc.unary_unary_rpc_method_handler(
            servicer.Analytics,
            request_deserializer=wellness__pb2.UserId.FromString,
            response_serializer=wellness__pb2.AnalyticsResponse.SerializeToString,
        ),
        "Recommendations": grpc.unary_unary_rpc_method_handler(
            servicer.Recommendations,
            request_deserializer=wellness__pb2.UserId.FromString,
            response_serializer=wellness__pb2.RecommendationsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "wellness.Wellness", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("wellness.Wellness", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Wellness(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpsertRecord(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wellness.Wellness/UpsertRecord",
            wellness__pb2.UpsertRecordRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RecordList(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wellness.Wellness/RecordList",
            wellness__pb2.Month.SerializeToString,
            wellness__pb2.RecordListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteAll(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wellness.Wellness/DeleteAll",
            wellness__pb2.UserId.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Dashboard(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wellness.Wellness/Dashboard",
            wellness__pb2.DashboardRequest.SerializeToString,
            wellness__pb2.DashboardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Analytics(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wellness.Wellness/Analytics",
            wellness__pb2.UserId.SerializeToString,
            wellness__pb2.AnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Recommendations(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/wellness.Wellness/Recommendations",
            wellness__pb2.UserId.SerializeToString,
            wellness__pb2.RecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
