{{- if .Values.monitoring.enabled }}
{{- $grafanaName := include "mind-journal.grafana.fullname" . -}}
{{- $prometheusName := include "mind-journal.prometheus.fullname" . -}}
{{- $lokiName := include "mind-journal.loki.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $grafanaName }}-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
    {{- include "mind-journal.labels" . | nindent 4 }}
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ $prometheusName }}:9090
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://{{ $lokiName }}:3100
{{- end }}
