{{- if and .Values.monitoring.enabled .Values.secrets.grafana }}
{{- $grafanaName := include "mind-journal.grafana.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $grafanaName }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
    {{- include "mind-journal.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.grafana }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
