{{- if .Values.monitoring.enabled }}
{{- $grafanaName := include "mind-journal.grafana.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $grafanaName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
    {{- include "mind-journal.labels" . | nindent 4 }}
spec:
  selector:
    app: grafana
  ports:
  - name: http
    port: {{ .Values.grafana.service.port }}
    targetPort: http
  type: ClusterIP
{{- end }}
