apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mind-journal.gateway.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: gateway
    {{- include "mind-journal.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.gateway.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  AUTH_SERVICE: {{ include "mind-journal.auth.fullname" . }}:{{ .Values.auth.service.grpcPort }}
  WELLNESS_SERVICE: {{ include "mind-journal.wellness.fullname" . }}:{{ .Values.wellness.service.grpcPort }}
  KAFKA_SERVICE: {{ include "mind-journal.kafka.fullname" . }}:9092
