apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mind-journal.gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: gateway
    {{- include "mind-journal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: "{{ .Values.global.image.repository }}:{{ .Values.gateway.image.tag }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.gateway.service.httpPort }}
          name: http
        envFrom:
        - configMapRef:
            name: {{ include "mind-journal.gateway.fullname" . }}-config
        startupProbe:
          httpGet:
            path: /api/health/live
            port: http
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health/live
            port: http
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health/ready
            port: http
          failureThreshold: 3
          periodSeconds: 5
        resources:
          {{- toYaml .Values.gateway.resources | nindent 10 }}
